### ISSUE TITLE
Change license to e.g. MIT?

### ISSUE THREAD

**Issue by devmotion** [LilithHafner/MallocArrays.jl#11]
Since AliasTables depends on PtrArrays, the license of PtrArrays is problematic for downstream packages such as Distributions or StatsBase that want to avoid (or at least minimize) GPL dependencies. See e.g. https://github.com/JuliaStats/Distributions.jl/issues/1864. Based on https://github.com/JuliaStats/Distributions.jl/issues/1864#issuecomment-2137579052, I assume it might be possible to relicense PtrArrays under the MIT license?

**Comment by LilithHafner** [comment]
@lkdvos, is this something you would be okay with?

**Comment by lkdvos** [comment]
Yes, completely fine by me, I don't know too much about the licencing but as far as I know tensoroperations also has MIT licence.
Thanks for asking!
