### ISSUE TITLE
DenseArray - support for strides

### ISSUE THREAD

**Issue by lkdvos** [LilithHafner/MallocArrays.jl#9]
I was wondering if it would be possible to bump `PtrArray` from a subtype of `AbstractArray` to a subtype of `DenseArray`. At first glance, as the memory layout is in fact dense and strided, it might make sense to make that explicit.

For me specifically, I would like to play around with these array types in the context of `TensorOperations.jl` and `Strided.jl`. There, contractions of multiple tensors often involves temporary array objects, and TensorOperations itself already inserts alloc and free calls within the generated code. It should thus be quite easy to plug PtrArrays in there, but the current implementation uses Strided.jl, which works on DenseArrays.

If this makes any sense, I'd be happy to drop a PR.

**Comment by LilithHafner** [comment]
From the docstring of DenseArray:

> N-dimensional dense array with elements of type T. The elements of a dense array are stored contiguously in memory.

I concur that PtrArray meets that definition and would be happy to accept a PR that updates that subtype, thanks!
